name: CI

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  pull_request:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the version of Node.js you want to use

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint  # Ensure you have a lint script in your package.json

  test:
    runs-on: ubuntu-latest
    needs: lint  # This ensures that lint runs before tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the version of Node.js you want to use

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test  # Ensure you have a test script in your package.json
